# Use the official Ubuntu base image
FROM ubuntu:22.04

# Avoid interactive prompts during package installs
ENV DEBIAN_FRONTEND=noninteractive

# Update packages and install basic utilities
RUN apt-get update && \
    apt-get install -y \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

COPY script.sh /app/script.sh

RUN chmod +x /app/script.sh

# Default command
CMD ["/bin/bash"]